default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight using App Store Connect API key"
  lane :beta do
    match(type: "development")
    build_app(scheme: "Mood")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
