name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: mh_user
          POSTGRES_PASSWORD: mh_pass
          POSTGRES_DB: mh_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do pg_isready -h localhost -p 5432 -U mh_user && break || sleep 1; done

      - name: Run migrations
        working-directory: backend
        env:
          DATABASE_URL: postgresql+psycopg2://mh_user:mh_pass@localhost:5432/mh_db
        run: |
          python -m alembic upgrade head

      - name: Run tests
        working-directory: backend
        env:
          DATABASE_URL: postgresql+psycopg2://mh_user:mh_pass@localhost:5432/mh_db
        run: |
          pytest -q
