name: Android Tests

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: ${{ env.ANDROID_SDK_ROOT }}
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/sdkmanager') }}
          restore-keys: |
            ${{ runner.os }}-android-sdk-

      - name: Cache diagnostics
        run: |
          echo "--- Cache diagnostic info ---"
          echo "Gradle cache key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}"
          echo "Android SDK cache key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/sdkmanager') }}"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          if [ -d "$ANDROID_SDK_ROOT" ]; then
            echo "SDK root exists, size:"; du -sh "$ANDROID_SDK_ROOT" || true
            echo "SDK root top-level entries:"; ls -1 "$ANDROID_SDK_ROOT" | sed -n '1,50p' || true
          else
            echo "SDK root not found: $ANDROID_SDK_ROOT"
          fi
          echo "Gradle cache size:"; du -sh ~/.gradle || true
          echo "Gradle wrapper directory:"; ls -ld ~/.gradle/wrapper || true
          echo "--- End cache diagnostic info ---"

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --info

      - name: Start Android emulator (reactivecircus)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86
          emulator-options: -no-window -no-audio -no-boot-anim

      - name: Run instrumentation tests
        run: ./gradlew connectedAndroidTest --info
        continue-on-error: false

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: android-app/app/build/reports
