name: Android Tests

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --info

      - name: Start Android emulator (reactivecircus)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86
          emulator-options: -no-window -no-audio -no-boot-anim

      - name: Run instrumentation tests
        run: ./gradlew connectedAndroidTest --info
        continue-on-error: false

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: android-app/app/build/reports
