name: Android JVM Unit Tests

on:
  push:
    paths:
      - 'android-app/**'
  pull_request:
    paths:
      - 'android-app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build and run unit tests
        run: ./gradlew testDebugUnitTest --info

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: app/build/test-results/testDebugUnitTest/
