name: Android Tests

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --info

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          target: default
          ndk: 'none'

      - name: Create and start emulator
        env:
          ADB_INSTALL_TIMEOUT: 20
        run: |
          echo 'no' | avdmanager create avd -n test -k "system-images;android-31;google_apis;x86" --force || true
          sudo /usr/bin/qemu-system-x86_64 -version || true
          nohup $ANDROID_SDK_ROOT/emulator/emulator -avd test -no-audio -no-window -gpu swiftshader_indirect &
          adb wait-for-device
          adb shell input keyevent 82 || true

      - name: Run instrumentation tests
        run: ./gradlew connectedAndroidTest --info
        continue-on-error: false

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: android-app/app/build/reports
